# Site settings
title: Heather You
header-img: img/home-bg.png
email: heatherhyou@gmail.com
copyright_name: Heather You
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: heatherhyou
github_username:  hyoyou
linkedin_username: heather-you
learn_profile: hyoyou
email_username: heatherhyou@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
